/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by OpenPort.
// You should NOT make any changes in this file as it will be overwritten.

// ---------------------------------------------------------------------------
// Plugin Registry
// ---------------------------------------------------------------------------

export type PluginName = 'authentication-better-auth' | 'authorization-duck-iam' | 'catalog' | 'unknown' | 'db-libsql' | 'events-s2' | 'nitro-server-plugin' | 'unknown' | 'unknown' | 'workflows-hatchet';

export interface PluginMetadata {
  name: PluginName;
  type: string;
  configKey: string;
  services: string[];
  features: string[];
  serverEvents: string[];
  clientEvents: string[];
}

export const PLUGIN_METADATA: PluginMetadata[] = 
[
  {
    "name": "authentication-better-auth",
    "type": "custom",
    "configKey": "authentication-better-auth",
    "services": [],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  },
  {
    "name": "authorization-duck-iam",
    "type": "custom",
    "configKey": "authorization-duck-iam",
    "services": [],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  },
  {
    "name": "catalog",
    "type": "custom",
    "configKey": "catalog",
    "services": [],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  },
  {
    "name": "unknown",
    "type": "custom",
    "configKey": "unknown",
    "services": [],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  },
  {
    "name": "db-libsql",
    "type": "data_store_provider",
    "configKey": "core_datastore",
    "services": [
      "db"
    ],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  },
  {
    "name": "events-s2",
    "type": "event_stream_provider",
    "configKey": "events-s2",
    "services": [
      "eventStream"
    ],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  },
  {
    "name": "nitro-server-plugin",
    "type": "custom",
    "configKey": "nitro-server-plugin",
    "services": [
      "nitroRegistry"
    ],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  },
  {
    "name": "unknown",
    "type": "custom",
    "configKey": "unknown",
    "services": [],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  },
  {
    "name": "unknown",
    "type": "custom",
    "configKey": "unknown",
    "services": [],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  },
  {
    "name": "workflows-hatchet",
    "type": "workflow",
    "configKey": "workflows-hatchet",
    "services": [],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  }
];

// ---------------------------------------------------------------------------
// Service Registry Augmentation
// ---------------------------------------------------------------------------

declare module '@op/platform/services' {
  interface ServiceRegistry {
    db: unknown;
    eventStream: unknown;
    nitroRegistry: unknown;
  }
}

// ---------------------------------------------------------------------------
// Config Type Map Augmentation
// ---------------------------------------------------------------------------

declare module '@op/platform/config' {
  interface ConfigTypeMap {
    'authentication-better-auth': unknown;
    'authorization-duck-iam': unknown;
    'catalog': unknown;
    'unknown': unknown;
    'core_datastore': unknown;
    'events-s2': unknown;
    'nitro-server-plugin': unknown;
    'workflows-hatchet': unknown;
  }
}

// ---------------------------------------------------------------------------
// Event Type Map Augmentation
// ---------------------------------------------------------------------------

declare module '@op/platform/events' {
  interface EventTypeMap {
  }
}

// ---------------------------------------------------------------------------
// Convenience Type Exports
// ---------------------------------------------------------------------------

export type ServiceName = 'db' | 'eventStream' | 'nitroRegistry';

export type ServerEventType = never;

export type ClientEventType = never;

export type FeatureFlagKey = never;
