import type { PluginMetadata } from "./plugin-parser.ts";

function yamlString(value: string): string {
  if (value.includes(":") || value.includes("#") || value.includes("'")) {
    return `'${value.replace(/'/g, "''")}'`;
  }
  return value;
}

export function generateOpenAPIFile(metadata: PluginMetadata[]): string {
  const lines: string[] = [
    "# Auto-generated by OpenPort - DO NOT EDIT",
    "openapi: 3.1.0",
    "info:",
    "  title: OpenPort Platform API",
    "  version: 0.0.0",
    "  description: Platform metadata generated from registered plugins",
    "",
    "x-openport-plugins:",
  ];

  for (const plugin of metadata) {
    lines.push(`  - name: ${yamlString(plugin.name)}`);
    lines.push(`    type: ${yamlString(plugin.type)}`);
    lines.push(`    configKey: ${yamlString(plugin.configKey)}`);

    if (plugin.services.length > 0) {
      lines.push("    services:");
      for (const service of plugin.services) {
        lines.push(`      - name: ${yamlString(service)}`);
      }
    }

    if (plugin.features.length > 0) {
      lines.push("    features:");
      for (const feature of plugin.features) {
        lines.push(`      - ${yamlString(feature)}`);
      }
    }

    lines.push("");
  }

  lines.push("x-openport-feature-flags:");
  for (const plugin of metadata) {
    if (plugin.features.length > 0) {
      lines.push(`  ${yamlString(plugin.name)}:`);
      for (const feature of plugin.features) {
        lines.push(`    ${yamlString(feature)}:`);
        lines.push("      type: unknown");
      }
    }
  }

  lines.push("");
  lines.push("x-openport-events:");

  const allServerEvents = metadata.flatMap((m) =>
    m.serverEvents.map((e) => ({ event: e, plugin: m.name, side: "server" })),
  );
  const allClientEvents = metadata.flatMap((m) =>
    m.clientEvents.map((e) => ({ event: e, plugin: m.name, side: "client" })),
  );

  for (const { event, plugin, side } of [...allServerEvents, ...allClientEvents]) {
    lines.push(`  - event: ${yamlString(event)}`);
    lines.push(`    plugin: ${yamlString(plugin)}`);
    lines.push(`    side: ${side}`);
  }

  lines.push("");
  lines.push("x-openport-config-sections:");

  for (const plugin of metadata) {
    lines.push(`  ${yamlString(plugin.configKey)}:`);
    lines.push(`    source: ${yamlString(plugin.name)}`);
  }

  lines.push("");
  lines.push("x-openport-services:");

  for (const plugin of metadata) {
    for (const service of plugin.services) {
      lines.push(`  ${yamlString(service)}:`);
      lines.push(`    plugin: ${yamlString(plugin.name)}`);
    }
  }

  lines.push("");

  return lines.join("\n");
}
