import type { PluginMetadata } from "./plugin-parser.ts";

function escapeString(str: string): string {
  return str.replace(/'/g, "\\'");
}

export function generateTypesFile(metadata: PluginMetadata[]): string {
  const pluginNames = metadata.map((m) => `'${escapeString(m.name)}'`);
  const allServices = metadata.flatMap((m) => m.services);
  const allServerEvents = metadata.flatMap((m) => m.serverEvents);
  const allClientEvents = metadata.flatMap((m) => m.clientEvents);
  const allFeatures = metadata.flatMap((m) => m.features);
  const configKeys = metadata.map((m) => m.configKey);

  const uniqueServices = [...new Set(allServices)];
  const uniqueServerEvents = [...new Set(allServerEvents)];
  const uniqueClientEvents = [...new Set(allClientEvents)];
  const uniqueFeatures = [...new Set(allFeatures)];
  const uniqueConfigKeys = [...new Set(configKeys)];

  const lines: string[] = [
    "/* eslint-disable */",
    "// @ts-nocheck",
    "// noinspection JSUnusedGlobalSymbols",
    "// This file was automatically generated by OpenPort.",
    "// You should NOT make any changes in this file as it will be overwritten.",
    "",
    "// ---------------------------------------------------------------------------",
    "// Plugin Registry",
    "// ---------------------------------------------------------------------------",
    "",
    `export type PluginName = ${pluginNames.length > 0 ? pluginNames.join(" | ") : "never"};`,
    "",
    "export interface PluginMetadata {",
    "  name: PluginName;",
    "  type: string;",
    "  configKey: string;",
    "  services: string[];",
    "  features: string[];",
    "  serverEvents: string[];",
    "  clientEvents: string[];",
    "}",
    "",
    "export const PLUGIN_METADATA: PluginMetadata[] = ",
    JSON.stringify(metadata, null, 2) + ";",
    "",
    "// ---------------------------------------------------------------------------",
    "// Service Registry Augmentation",
    "// ---------------------------------------------------------------------------",
    "",
    "declare module '@op/platform/services' {",
    "  interface ServiceRegistry {",
    ...uniqueServices.map((s) => `    ${s}: unknown;`),
    "  }",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Config Type Map Augmentation",
    "// ---------------------------------------------------------------------------",
    "",
    "declare module '@op/platform/config' {",
    "  interface ConfigTypeMap {",
    ...uniqueConfigKeys.map((k) => `    '${escapeString(k)}': unknown;`),
    "  }",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Event Type Map Augmentation",
    "// ---------------------------------------------------------------------------",
    "",
    "declare module '@op/platform/events' {",
    "  interface EventTypeMap {",
    ...uniqueServerEvents.map((e) => `    '${escapeString(e)}': unknown;`),
    "  }",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Convenience Type Exports",
    "// ---------------------------------------------------------------------------",
    "",
    `export type ServiceName = ${uniqueServices.length > 0 ? uniqueServices.map((s) => `'${escapeString(s)}'`).join(" | ") : "never"};`,
    "",
    `export type ServerEventType = ${uniqueServerEvents.length > 0 ? uniqueServerEvents.map((e) => `'${escapeString(e)}'`).join(" | ") : "never"};`,
    "",
    `export type ClientEventType = ${uniqueClientEvents.length > 0 ? uniqueClientEvents.map((e) => `'${escapeString(e)}'`).join(" | ") : "never"};`,
    "",
    `export type FeatureFlagKey = ${uniqueFeatures.length > 0 ? uniqueFeatures.map((f) => `'${escapeString(f)}'`).join(" | ") : "never"};`,
    "",
  ];

  return lines.join("\n");
}
