/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by OpenPort.
// You should NOT make any changes in this file as it will be overwritten.

// ---------------------------------------------------------------------------
// Plugin Registry
// ---------------------------------------------------------------------------

export type PluginName = 'catalog';

export interface PluginMetadata {
  name: PluginName;
  type: string;
  configKey: string;
  services: string[];
  features: string[];
  serverEvents: string[];
  clientEvents: string[];
}

export const PLUGIN_METADATA: PluginMetadata[] = 
[
  {
    "name": "catalog",
    "type": "custom",
    "configKey": "catalog",
    "services": [],
    "features": [],
    "serverEvents": [],
    "clientEvents": []
  }
];

// ---------------------------------------------------------------------------
// Service Registry Augmentation
// ---------------------------------------------------------------------------

declare module '@op/platform/services' {
  interface ServiceRegistry {
  }
}

// ---------------------------------------------------------------------------
// Config Type Map Augmentation
// ---------------------------------------------------------------------------

declare module '@op/platform/config' {
  interface ConfigTypeMap {
    'catalog': unknown;
  }
}

// ---------------------------------------------------------------------------
// Event Type Map Augmentation
// ---------------------------------------------------------------------------

declare module '@op/platform/events' {
  interface EventTypeMap {
  }
}

// ---------------------------------------------------------------------------
// Convenience Type Exports
// ---------------------------------------------------------------------------

export type ServiceName = never;

export type ServerEventType = never;

export type ClientEventType = never;

export type FeatureFlagKey = never;
