apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nodejs-slim
  title: nodejs-slim
  description: Utility tool managed via devbox
  tags:
    - devbox
    - cli
    - utility
spec:
  type: utility
  owner: platform-team
