// Code generated by dagger. DO NOT EDIT.
//
// This file provides type stubs for the dagger module SDK.
// Run `dagger develop` (with dagger CLI available) to regenerate with full
// SDK bindings from the dagger engine at src/ops/platform/dagger.json.
//
// The real dagger engine injects these at runtime; this stub satisfies the
// Go compiler for local development without a running dagger engine.
package main

import "context"

// Directory represents a filesystem directory in dagger.
// The real type is provided by the dagger engine at runtime.
type Directory = dagDirectory

// Secret represents a secret value in dagger.
type Secret = dagSecret

// Service represents a long-running Dagger service (container exposed as a network endpoint).
type Service = dagService

// dagDirectory is the stub implementation of Directory.
type dagDirectory struct{ path string }

// WithNewFile returns a new Directory with a new file at path with the given contents.
func (d *dagDirectory) WithNewFile(path, contents string) *dagDirectory { return d }

// dagSecret is the stub implementation of Secret.
type dagSecret struct{ name string }

// Plaintext returns the plaintext value of the secret.
func (s *dagSecret) Plaintext(ctx context.Context) (string, error) { return s.name, nil }

// dagService is the stub implementation of a Dagger service.
type dagService struct{}

// dagContainer is the stub implementation of a dagger container.
type dagContainer struct{}

func (c *dagContainer) From(image string) *dagContainer                                   { return c }
func (c *dagContainer) WithMountedDirectory(path string, dir *dagDirectory) *dagContainer { return c }
func (c *dagContainer) WithWorkdir(path string) *dagContainer                             { return c }
func (c *dagContainer) WithExec(args []string) *dagContainer                              { return c }
func (c *dagContainer) WithSecretVariable(name string, secret *dagSecret) *dagContainer   { return c }
func (c *dagContainer) WithEnvVariable(name, value string) *dagContainer                  { return c }
func (c *dagContainer) WithExposedPort(port int) *dagContainer                            { return c }
func (c *dagContainer) WithServiceBinding(alias string, svc *dagService) *dagContainer    { return c }
func (c *dagContainer) AsService() *dagService                                            { return &dagService{} }
func (c *dagContainer) Sync(ctx context.Context) (*dagContainer, error)                   { return c, nil }
func (c *dagContainer) Stdout(ctx context.Context) (string, error)                        { return "", nil }
func (c *dagContainer) Stderr(ctx context.Context) (string, error)                        { return "", nil }

// dagClient is the stub dagger client.
type dagClient struct{}

func (d *dagClient) Container() *dagContainer           { return &dagContainer{} }
func (d *dagClient) SetSecret(name, val string) *Secret { return &dagSecret{name: name} }
func (d *dagClient) Directory() *dagDirectory           { return &dagDirectory{} }

// dag is the global dagger client, injected by the dagger engine at runtime.
// This stub is replaced by the engine-provided client when running via `dagger call`.
var dag dagInterface = &dagClient{}

// dagInterface allows the real engine client to be substituted at runtime.
type dagInterface interface {
	Container() *dagContainer
	SetSecret(name, val string) *Secret
	Directory() *dagDirectory
}
